FROM maven AS buildstage 
RUN mkdir /opt/Naveen-CI-CD-Project
WORKDIR /opt/Naveen-CI-CD-Project
COPY . .
RUN mvn clean install ###########---> *.war


FROM tomcat 
WORKDIR webapps
COPY --from=buildstage /opt/Naveen-CI-CD-Project/target/*.war .
RUN rm -rf ROOT && mv *.war ROOT.war
EXPOSE 8080
