apiVersion: apps/v1
kind: Deployment

metadata:
  name: naveen-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: naveen-app

  template:
    metadata:
      labels:
        app: naveen-app

    spec:
      containers:

      - name: naveen-app

        image: naveengudugula/naveen-ci-cd:v1

        ports:
        - containerPort: 8080
